// Generated by CoffeeScript 1.9.2
var jsyaml;

jsyaml = require('js-yaml');

module.exports = {
  unary: {
    yaml: function(exe, params) {
      var getsource;
      getsource = exe.build(params.__s);
      return function(cb) {
        return getsource(function(err, source) {
          var e;
          if (err != null) {
            return cb(err);
          }
          try {
            return cb(null, jsyaml.load(source));
          } catch (_error) {
            e = _error;
            return cb(e);
          }
        });
      };
    }
  }
};
